### ISSUE TITLE
Include the latest stable version of Microsoft.Owin (4.0.0) in dependencies

### ISSUE THREAD

**Issue by adamante** [autofac/Autofac.Owin#16]
Hello! 

Microsoft have just released an update of all Microsoft.Owin.* NuGet packages from 4.0.0-preview1 to 4.0.0 stable. But I can't update update to stable due to Autofac dependency (Microsoft.Owin < 4.0.0, so strictly less). 

My app works fine with a current Autofac.Owin package and a preview from Microsoft, and from what I've seen they didn't introduce breaking changes in 4.0.0, so please consider validating and including 4.0.0 stable in your NuGet package dependencies. 

Thanks.

**Comment by springy76** [comment]
NuGet+SemVer seems to be broken by design. I upgraded Owin to 4.0.0-preview1 months ago and never got any warning since in SemVer 4.0.0-preview1 is less than 4.0.0 and so is "compatible" with `version="[3.0.0,4.0.0)"`. I wonder how to do this right?

**Comment by tillig** [comment]
Looks like if we keep the semver for `Autofac.Owin` in the 4.x range we shouldn't have to modify the `Autofac.WebApi.Owin` or `Autofac.Mvc.Owin` packages.

Code changes are done and pushed to develop but I need to test the upgrade scenario to make sure things don't break somewhere unexpected.

**Comment by tillig** [comment]
[Released Autofac.Owin 4.2.0 with this included.](https://www.nuget.org/packages/Autofac.Owin/4.2.0)

**Comment by huysentruitw** [comment]
Great service 👌

**Comment by springy76** [comment]
Boy I hate it to be negative but your NuGet package hierarchy is a *NIGHTMARE* when used with the new transitive package references.

I started (months ago) with `<PackageReference Include="Autofac.WebApi2.Owin" Version="4.0.0" />` which created a wild mix of very dated libs because it loaded Autofac.WebApi 3.4.0. So I had to manually add `<PackageReference Include="Autofac.WebApi2" Version="4.1.0" />`.

But now I still don't see your Autofac.Owin 4.2.0 update because the entire tooling just ignores any transitive references.
Now I have to add `<PackageReference Include="Autofac.Owin" Version="4.2.0" />` manually which renders the entire transitive reference system useless.
