### ISSUE TITLE
Middleware injection doesn't work with ACTNARS

### ISSUE THREAD

**Issue by alexkolt** [autofac/Autofac.Owin#9]
In my registration if I have the following the middlewares never fire.

builder.RegisterSource(new AnyConcreteTypeNotAlreadyRegisteredSource());

**Comment by alexmg** [comment]
Do you have a simple example that reproduces this issue? It sounds like a weird one and there isn't much to go on here.

**Comment by alexkolt** [comment]
I'll work to get an example out this weekend.

**Comment by tillig** [comment]
I was able to replicate the issue in this project:
[WebApplication1.zip](https://github.com/autofac/Autofac.Owin/files/340204/WebApplication1.zip)

I'm not sure what the root cause is yet, but it's reproduced.

**Comment by tillig** [comment]
The problem appears to be in the `AutofacAppBuilderExtensions` class in `UseAllMiddlewareRegisteredInContainer`. Specifically, we get the list of middleware like this:

```csharp
var services = container.ComponentRegistry.Registrations.SelectMany(r => r.Services)
    .OfType<TypedService>()
    .Where(s => s.ServiceType.IsAssignableTo<OwinMiddleware>() && !s.ServiceType.IsAbstract)
    .Select(service => typeof(AutofacMiddleware<>).MakeGenericType(service.ServiceType))
    .Where(serviceType => !container.IsRegistered(serviceType));
```

With ACTNARS registered, that last bit `.Where(serviceType => !container.IsRegistered(serviceType))` fails because it thinks _everything_ is registered. I'm guessing the real intention of this filter was to get rid of any accidental inclusion of `AutofacMiddleware<T>` itself.

Let me see if I can fix that up.

**Comment by tillig** [comment]
As soon as the build completes I'll be pushing a new version. This will probably be the 4.0.0 release/stable version.
